############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088

############################################################
#
# Data Source Config
#
############################################################
spring:
  datasource:                                         # 数据源的相关配置
    url: jdbc:mysql://192.168.31.46:3306/foodie_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: abc123456
  redis:
    database: 0
    host: 192.168.31.213
    password: moka_cheng

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl